version: "3.9"
services:
  apache-event: 
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "19002:80"
    volumes:
      - ./src:/var/www/html
    tty: true
    privileged: true
